# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    authentication_handler:
            class: AppBundle\Listener\AuthenticationHandler
            arguments: ["@request_stack"]
            tags:
                - { name: kernel.event_listener, event: security.authentication.success, method: onAuthenticationSuccess }
